### PR TITLE
add pycache to gitignore

### PR DESCRIPTION
**Pull request by coltongit**
Port pycache gitignore addition from mid-kid's i18n work (based on https://github.com/mid-kid/pokecrystal/commit/b6914f3c06d1459b324f39c2e8e5bf6c8f52aaa5)

### CODE REVIEW

**Comment by vulcandth** [comment]
Why are we adding this?

**Comment by coltongit** [comment]
> Why are we adding this?

In case pycache files are somehow dropped into the source directory, wouldn't want to clutter the repo with them needlessly

**Comment by Idain** [comment]
But we haven't had any problems with them. If someone wants to avoid it for their personal project, that's their responsibility.

**Comment by coltongit** [comment]
I'll close this for now, if it does become a problem in the future I'll rebase and we'll have another look

**Comment by mid-kid** [comment]
`*.pyc` should be enough to ignore the `__pycache__` dir anyway.

**Comment by mid-kid** [comment]
I think it's good to have ignores for common files that are generated by the tools we have in this repo, or are frequently used in combination with this repo. Yes that includes pycache and mac files, though vim is arguable.

**Comment by mid-kid** [comment]
> Didn't realise there were python files in the repo (for compiling the images I guess?)

They're auxiliary tools not involved in the build process but useful for a few things.

> If we're ignoring mac files we should be ignoring windows files too, plus whatever android and every 9000 file managers on linux decide to make. Using a mac is a choice, and not one everyone makes.

Mac is the only platform that generates files that git can pick up like this. Thumbs.db on windows is hidden and doesn't get picked up, and the 9000 file managers on linux don't create files like this either.

I very much prefer avoiding people shooting themselves in the foot with this. Our audience is people who might be unaware of the existence of this metadata file, let alone know about advanced git configuration.

**Comment by mid-kid** [comment]
> Didn't realise there were python files in the repo (for compiling the images I guess?)

They're auxiliary tools not involved in the build process but useful for a few things.

> If we're ignoring mac files we should be ignoring windows files too, plus whatever android and every 9000 file managers on linux decide to make. Using a mac is a choice, and not one everyone makes.

Mac is the only platform that generates files that git can pick up like this. Thumbs.db on windows is hidden and doesn't get picked up, and the 9000 file managers on linux don't create files like this either.

I very much prefer avoiding people shooting themselves in the foot with this. Our audience is people who might be unaware of the existence of this metadata file, let alone know about advanced git configuration.

**Pull request closed without merging**
