### PR TITLE
Clarify how wCurBattleMon works

### PR DESCRIPTION
**Pull request by Idain**

### CODE REVIEW

**Comment by Rangi42** [comment]
It's for symmetry with `wCurPartyMon`, but frankly I'd rather remove that comment too. The label already tells you it's the cur(rent) (Poke)mon, and indexes naturally start from 0.

**Comment by Idain** [comment]
1. It saves time so that one doesn't have to look at the code to figure out how it works.
2. I was replicating the style `wCurPartyMon`'s comment used. I can reduce it to two lines or even one if necessary.

**Comment by Idain** [comment]
> 

You'd be surprised how easy people can get confused. I'd rather leave that comment (although it could be reduced to two lines if necessary).

**Comment by Rangi42** [comment]
Alright, please do reformat both to two lines. Also can you open PRs for pokegold too when they're applicable to it?

**Comment by aaaaaa123456789** [comment]
It could be much shorter and not even two lines: `; index of the player's mon currently in battle (0-5)`

**Comment by Idain** [comment]
Ok, both comments have been reformated.

**Comment by Idain** [comment]
Mmm. The maybe something like `; index of mon's current party location` could work?

**Comment by mid-kid** [comment]
Nitpick, but I prefer
```
; comment
wVar:: db
```

The file currently contains a bit of both styles which bothers me.

Also "current" is about as descriptive as "buffer", it doesn't really denote what its purpose is. One "current" means "storage for value that reflects battle state" while the other "current" means "function parameter with no relevance to the game state". This definitely deserves a comment.

As for a comment, `; index of the mon in the party that's being processed (0-5)` maybe?

**Comment by Idain** [comment]
That comment works for me? Anyone else has something to say?

**Pull request merged**
