### PR TITLE
Document the glitch dimension!

### PR DESCRIPTION
**Pull request by coltongit**

### CODE REVIEW

**Comment by coltongit** [comment]
oh wait this should probably be moved to pokegold

**Comment by coltongit** [comment]
oh wait again... I forgot this could still affect pokecrystal in a different manner, locking out the game after the tricks are done

**Comment by Rangi42** [comment]
Not a bug.

**Comment by coltongit** [comment]
Is for pokegold though, reopened there (https://github.com/pret/pokegold/pull/93)

**Pull request closed without merging**
