### PR TITLE
Link code improvements

### PR DESCRIPTION
**Pull request by mid-kid**

### CODE REVIEW

**Comment by mid-kid** [comment]
As a side-note, it's very tempting to nuke the wLinkData unions (link data members, link mail data, received link mail data).
Primarily because wLinkData is a generic temporary buffer for various operations, and its layout is slightly floaty (depending on how the data rolls in), and the layout of the data during sending is very different than the one used during reception. This same symptom can be seen in "link mail data" vs "received link mail data". It's very confusing to follow code that uses the different union sections interchangeably, since it's not always clear that the data being consumed is the same that was received just a second ago, not some new data.
Only one label is used within the "link data members" section: wLinkPlayerData (and its alternate name wTimeCapsulePlayerData).

**Review by vulcandth — APPROVED** [review]
Looks good over the cursory look. If you are confident with it i'm good with it. If not, I can do a deep dive review. Let me know.

**Comment by mid-kid** [comment]
@vulcandth The only change I'm not confident about I've outlined above in the previous comment, though it isn't part of this PR. That said, I'd like for @Rangi42 to take a cursory look as well.

**Review by aaaaaa123456789 — APPROVED** [review]
Looks good to me, and I'd be very happy to see the `wLinkData` fake union nuked into orbit.

**Review by Rangi42 — APPROVED** [review]

**Comment by Rangi42** [comment]
Looks good to me! Nice work!

pokegold will need this and the last few commits ported too.

**Comment by mid-kid** [comment]
Oh, right. Pokegold. Will do.

**Comment by vulcandth** [comment]
@mid-kid if you have time can you take a peak at pokered. I think many of these improvements to the link code can be brought over there too. I can do that work. Just wanted you to give a quick glance since the link code is fresh on your mind.. and hopefully you can identify some potential improvements we can backport over there. If you don't have the time no worries.

**Comment by mid-kid** [comment]
I'll be honest I've hardly looked at the gen1 parts of the link code, though it works similarly, so I might check it out.

**Comment by vulcandth** [comment]
> Looks good to me! Nice work!
> 
> pokegold will need this and the last few commits ported too.

@Rangi42 I've been keeping pokegold up to date already. The last few commits of pokecrystal are not applicable to pokegold, the ones that were I've already ported.

**Pull request merged**
