### PR TITLE
Use `{interpolation}` to generate sequences of RAM labels

### PR DESCRIPTION
**Pull request by Rangi42**
This makes the `table_width`/`assert_table_length` usages unnecessary, and also keeps the labels automatically up to date if the length constants change.

### CODE REVIEW

**Comment by aaaaaa123456789** [comment]
I'm not too sure about the PC boxes — I don't like the use of `NUM_BOXES / 2`, particularly because it prevents simple upgrades (say, migrating to MBC30 and using extra box banks). Other than that, I love it.

**Comment by Rangi42** [comment]
I see your point about `NUM_BOXES / 2`. What if it were like this:


```
; in constants/pokemon_data_constants.asm
MONS_PER_BOX EQU 20
NUM_BOXES EQU 14
BOX_LENGTH EQU 1 + MONS_PER_BOX + 1 + (BOXMON_STRUCT_LENGTH + NAME_LENGTH + MON_NAME_LENGTH) * MONS_PER_BOX + 2 ; $450
BOXES_PER_BANK EQU (SRAM_End - SRAM_Begin) / BOX_LENGTH ; 7 boxes can fit in an SRAM bank


SECTION "Boxes 1-7", SRAM

; sBox1 - sBox7
for n, 1, BOXES_PER_BANK + 1
sBox{d:n}:: box sBox{d:n}
endr


SECTION "Boxes 8-14", SRAM

; sBox8 - sBox14
for n, BOXES_PER_BANK + 1, NUM_BOXES + 1
sBox{d:n}:: box sBox{d:n}
endr
```

Then `"Boxes 8-14"` would overflow if you increase `NUM_BOXES`, but you could do:

```
SECTION "Boxes 8-14", SRAM

; sBox8 - sBox14
for n, BOXES_PER_BANK + 1, BOXES_PER_BANK * 2 + 1
sBox{d:n}:: box sBox{d:n}
endr


SECTION "Boxes 15+", SRAM

; sBox15+
for n, BOXES_PER_BANK * 2 + 1, NUM_BOXES + 1
sBox{d:n}:: box sBox{d:n}
endr
```

**Comment by aaaaaa123456789** [comment]
I'd just leave it as `for n, BOXES_PER_BANK + 1, BOXES_PER_BANK * 2 + 1` for the second bank, and assert `NUM_BOXES` if needed.

**Comment by Rangi42** [comment]
Another alternative, possibly easier to extend, especially with an uneven layout like (7+7+4+2):

```
; The PC boxes will not fit into one SRAM bank,
; so they use multiple SECTIONs
box_n = 1

SECTION "Boxes 1-7", SRAM

; sBox1 - sBox7
for box_n, box_n, box_n + 7
sBox{d:box_n}:: box sBox{d:box_n}
endr


SECTION "Boxes 8-14", SRAM

; sBox8 - sBox14
for box_n, box_n, box_n + 7
sBox{d:box_n}:: box sBox{d:box_n}
endr

; All 14 boxes fit exactly within 2 SRAM banks
assert box_n == NUM_BOXES + 1
```

**Comment by aaaaaa123456789** [comment]
I feel like `for var, var, var + offset` is confusing for just about everyone.

```
box_number = 0
boxes: MACRO
  rept \1
box_number = box_number + 1
sBox{d:box_number}:: box sBox{d:box_number}
  endr

; and the sections and the assert
```

**Comment by Kroc** [comment]
Does the ASM code assume contiguity between boxes? What if the macro created a separate Section for every box? This would scale better with changes in box count.

**Comment by Rangi42** [comment]
```
SECTION "a", SRAM
...stuff...
 boxes 1

SECTION "b", SRAM
 boxes 1
...more stuff...

SECTION "c", SRAM
...and more...
 boxes 1
...here too...
```

All that matters is initializing `box_n = 0` and finally asserting `box_n == NUM_BOXES`.

**Pull request merged**
