### PR TITLE
wVirtualOAM -> wShadowOAM and hTransferVirtualOAM -> hTransferShadowOAM

### PR DESCRIPTION
**Pull request by coltongit**
ISSOtm, as he pointed out in https://github.com/pret/pokecrystal/pull/943#discussion_r906649489, noticed that the WRAM constant `wVirtualOAM` is, by most usage and convention elsewhere, known as `wShadowOAM` instead.
This PR aims to rename this particular WRAM constant so that it matches this convention.
Supersedes and resolves #970
pokegold companion PR: https://github.com/pret/pokegold/pull/99
pokegold-spaceworld companion PR: https://github.com/pret/pokegold-spaceworld/pull/103
pokered companion PR: https://github.com/pret/pokered/pull/370

### CODE REVIEW

**Comment by vulcandth** [comment]
> Where did we start or want to start a "shadow" naming convention?

In case you were looking for @ISSOtm 's comment buried deep within the `hardware.inc` PR..... I found it. https://github.com/pret/pokecrystal/pull/943#discussion_r906649489

**Comment by Rangi42** [comment]
I'm indifferent to "shadow" vs "virtual" OAM, but *after* we agree on one, Gen 1's `wOAMBuffer` should get the same name.

**Comment by ISSOtm** [comment]
Because the term "shadow" is used commonly in the field for a "cache" residing elsewhere in memory; "virtual" implies something else. "Shadow" is used in other GB dev material, but I don't think I have seen "virtual" for that purpose.

**Comment by Rangi42** [comment]
Alright, "shadow" is fine then. @coltongit Please do the same for red+yellow.

**Comment by coltongit** [comment]
> Alright, "shadow" is fine then. @coltongit Please do the same for red+yellow.

Done.

**Comment by Rangi42** [comment]
This should rename `hTransferVirtualOAM` too.

**Comment by Rangi42** [comment]
> Because the term "shadow" is used commonly in the field for a "cache" residing elsewhere in memory; "virtual" implies something else. "Shadow" is used in other GB dev material, but I don't think I have seen "virtual" for that purpose.

Turns out we got "virtual" from you. :P 

https://discord.com/channels/306193495234707456/318221301615558667/405470471086407710 

https://github.com/ISSOtm/Aevilia-GB/blob/master/main/wram.asm#L233-L237

**Comment by coltongit** [comment]
> This should rename `hTransferVirtualOAM` too.

Did that as well for both pokegold and pokecrystal

**Comment by ISSOtm** [comment]
> @ISSOtm Turns out we got "virtual" from you. :P 
> https://github.com/ISSOtm/Aevilia-GB/blob/master/main/wram.asm#L233-L237

Honestly, I'll be glad another piece of that "don't reuse any code from there" project's legacy gets done away with. 😅

**Review by Rangi42 — APPROVED** [review]

**Comment by ISSOtm** [comment]
Thank you!

**Comment by Rangi42** [comment]
(I like how much rgbds has improved; Aevilia's `dline` macro can now be just:)
```
MACRO dline
{line_prefix}\1::
	shift
	db \#, 0
ENDM
```

**Pull request merged**
