### PR TITLE
Document scripting engine fix for MBC30

### PR DESCRIPTION
**Pull request by mid-kid**

### CODE REVIEW

**Comment by mid-kid** [comment]
Turns out the bit it's masking was used for something, drafting...

**Comment by mid-kid** [comment]
Fixed

**Review by vulcandth — APPROVED** [review]
Makes sense and looks good to me. Assuming you tested it already (I'm sure you have), you can merge it unless you want Rangi to take at look as well.

**Comment by mid-kid** [comment]
I haven't extensively tested this, but I've checked every use of wScriptBank and wScriptStack and nothing indicated it's actually being used anywhere, so I think it's fine.

**Pull request merged**
