### PR TITLE
Resolve issue with Full Heal text not updating correctly after bugfix

### LINKED ISSUE #818: Full Heal text isn't displayed correctly after applying "AI use of Full Heal does not cure confusion status" bugfix
This bugfix has a problem, and is that whenever the AI uses the Full Heal item the name is replaced with "?" instead:

[Example of Full Heal text being displayed incorrectly](https://user-images.githubusercontent.com/54337884/112940080-9de22780-90fa-11eb-9286-f703a3e7756c.png)

**NOTE:** The person who took the screenshot also tested the bugfix with a clean version of pokecrystal and this error still happened.

The cause of this problem is that, in `EnemyFullHeal`, register `a` contains the item used, gets stored in `[wCurEnemyItem]` and then `xor a` deletes this value.
```diff
 EnemyUsedFullHeal:
 	call AIUsedItemSound
 	call AI_HealStatus
 	ld a, FULL_HEAL
+	ld [wCurEnemyItem], a
+	xor a
+	ld [wEnemyConfuseCount], a
 	jp PrintText_UsedItemOn_AND_AIUpdateHUD
```
However, the first instruction in `PrintText_UsedItemOn_AND_AIUpdateHUD` tries store the value of `a` into `[wCurEnemyItem]` and, since it's 0, it can't print it properly.
```
; Parameter
; a = ITEM_CONSTANT
PrintText_UsedItemOn_AND_AIUpdateHUD:
	ld [wCurEnemyItem], a
	call PrintText_UsedItemOn
	jp AIUpdateHUD
```
**SOLUTION:** Only add `ld [wEnemyConfuseCount], a` before `ld a, FULL_HEAL` in `EnemyUsedFullHeal`. Register `a` already gets cleaned in `AI_HealStatus`, so we don't need to perform another `xor a`:
```diff
EnemyUsedFullHeal:
	call AIUsedItemSound
	call AI_HealStatus
+	ld [wEnemyConfuseCount], a
	ld a, FULL_HEAL
	jp PrintText_UsedItemOn_AND_AIUpdateHUD
```

### PR DESCRIPTION
**Pull request by coltongit**
Fixes #818 by implementing the suggested bugfix change by @i0brendan0.

### CODE REVIEW

**Comment by Rangi42** [comment]
Please test this fix and see if it works.

**Comment by Rangi42** [comment]
Also remember to [view](https://github.com/coltongit/pokecrystal/blob/patch-1/docs/bugs_and_glitches.md) your edits on your own GitHub to make sure they look correct.

**Comment by Idain** [comment]
I'll see if I can test it in the next few days. This PR has been open foe so long.

**Comment by vulcandth** [comment]
Tested in game; This appears to fix the Text as well as enable Full Heal to cure confusion in game.

**Comment by vulcandth** [comment]
If there is merge conflicts on this PR; is @coltongit still around to resolve them? If not I could open a new PR to resolve them and help get this PR closed.

**Comment by Idain** [comment]
I'm surprised @Rangi42 hasn't said anything, or any mod.

**Comment by vulcandth** [comment]
> I'm surprised @Rangi42 hasn't said anything, or any mod.

I imagine they have been quite busy. And this is very low priority. I'm only offering to help resolve conflicts to make it easier for them.

**Comment by Rangi42** [comment]
There's a merge conflict with some other change to the same file.

**Comment by Rangi42** [comment]
Replaced by #887.

**Pull request closed without merging**
