### PR TITLE
Use def_* macros for automatic map event counts

### LINKED ISSUE #742: Automatically insert correct map event counts with macros
It's easy to forget to update the `db` counts for `warp_event`s, `object_event`s, etc, which will build correctly but can cause obscure bugs. An automatic solution—ideally one that still just requires one line at the top of each event block—would be nice.

This one-line example will work in the next rgbds release, though it does not in 0.4.0:

```
def_warp_events: MACRO
	db NUM_WARP_EVENTS
NUM_WARP_EVENTS = 0
ENDM

warp_event: MACRO
NUM_WARP_EVENTS = NUM_WARP_EVENTS + 1
	...
ENDM

	def_warp_events
	warp_event  6,  7, NEW_BARK_TOWN, 2
	warp_event  7,  7, NEW_BARK_TOWN, 2
	warp_event  9,  0, PLAYERS_HOUSE_2F, 1
```

This two-line solution works now:

```
def_warp_events: MACRO
    db (.End_Warp_Events - .Warp_Events) / WARP_EVENT_SIZE
.Warp_Events
ENDM

end_warp_events: MACRO
.End_Warp_Events
ENDM

	def_warp_events
	warp_event  6,  7, NEW_BARK_TOWN, 2
	warp_event  7,  7, NEW_BARK_TOWN, 2
	warp_event  9,  0, PLAYERS_HOUSE_2F, 1
	end_warp_events
```

### PR DESCRIPTION
**Pull request by Rangi42**
Resolves #742

### CODE REVIEW

**Comment by aaaaaa123456789** [comment]
I have mixed feelings about this PR. It will certainly eliminate a common pain point, but it also looks like a giant hack that will break in five minutes.

**Comment by Rangi42** [comment]
@aaaaaa123456789 How so? It has the same failure modes as the former `db`s, where you might omit a `def_*`  line or define an event before its `def_*` line (although I doubt either of those errors is common), but makes impossible the more likely failure of getting the number wrong.

**Comment by aaaaaa123456789** [comment]
It's the lazy evaluation of redefined constants what makes me uneasy.

**Comment by Rangi42** [comment]
Well, they're not quite redefined; the "`\@`" creates a new constant for each map (`_NUM_SCENE_SCRIPTS_0`, `_NUM_SCENE_SCRIPTS_1`, `_NUM_CALLBACKS_0`, etc). The strings like `_NUM_SCENE_SCRIPTS` and `_NUM_CALLBACKS` do get purged and redefined for each map, but that's a standard rgbds feature, essential for things like [rgbds-structs](https://github.com/ISSOtm/rgbds-structs/blob/master/structs.asm), so its behavior isn't going to change unexpectedly.

**Comment by aaaaaa123456789** [comment]
I guess that `PURGE` isn't about to break...

**Comment by ISSOtm** [comment]
I just reviewed this, and this is absolutely defined, and perhaps the cleanest implementation of this. The `equs` is stored in-place, and in fact the `\@` is expanded when the string is read anyways, so even if evaluation was to become lazy, this would still work.

Note that the way the current lexer works does make this prone to breaking (macro args expansions have to be explicitly handled everywhere), but the one I'm currently writing should stabilize this. (And keep the behavior.)

**Comment by Rangi42** [comment]
> macro args expansions have to be explicitly handled everywhere

Can you explain how this might break due to that? I tested omitting a `def_` macro and putting an event macro before its heading `def_` macro, and in both cases, it just assembled without errors, same as the current `db` solution. (Of course the data would be wrong, but that's expected. The macros could have error checking for those kind of mistakes, but it's probably not worth the extra complexity.)

**Comment by ISSOtm** [comment]
I'm saying that if a change were to be made to the current lexer that forgot to handle macro args, they'd be essentially deferred, breaking this. My actual point was that the new lexer will be much more reliable as far as this functionality goes.

**Pull request merged**
