### PR TITLE
Replace hardcoded number

### PR DESCRIPTION
**Pull request by Idain**
I noticed this hardcoded value some time ago, and there are probably more cases in this file. If that's the case, please let me know to add more commits to this PR.

### CODE REVIEW

**Comment by Rangi42** [comment]
`wBaseStats` and `EnemyMonBaseStats` are structs of 6, bytes, not 5; `NUM_STATS` is 6. Why does this loop stop before copying SpDef? Is it a bug? Are there any moves that work with the mons' base SpDef, and do they use the wrong value due to this?

**Comment by Idain** [comment]
`b` decreases to 0 when it copies the value from `wBaseSpecialDefense` to the last byte of `wEnemyMonStats`, making the loop stop and working as expected.

**Comment by Idain** [comment]
I remember that `wEnemyMonBaseStats` is used for Stat Exp. calculation, so that explains why it doesn't copy the Pokémon's base Sp. Def. (the enemy's base Sp. Atk is added to both the user's Sp. Atk and Sp. Def).

**Comment by Rangi42** [comment]
> I remember that `wEnemyMonBaseStats` is used for Stat Exp. calculation, so that explains why it doesn't copy the Pokémon's base Sp. Def. (the enemy's base Sp. Atk is added to both the user's Sp. Atk and Sp. Def).

Good to know! In that case, please use `NUM_STATS - 1` for the `5` constant, with a comment explaining that Sp. Def doesn't need copying since the enemy mon's base Sp. Atk is used to calculate Sp. Def stat experience.

**Comment by Idain** [comment]
Something similar happens in lines [3983](https://github.com/pret/pokecrystal/blob/fabdd8e0196d1c50ee0a4a40823d0f8a0372d93c/engine/battle/core.asm#L3983) and [6368](https://github.com/pret/pokecrystal/blob/fabdd8e0196d1c50ee0a4a40823d0f8a0372d93c/engine/battle/core.asm#L6368). Do you think we should also replace them with `NUM_STATS - 1`?

**Comment by Rangi42** [comment]
> Something similar happens in lines [3983](https://github.com/pret/pokecrystal/blob/fabdd8e0196d1c50ee0a4a40823d0f8a0372d93c/engine/battle/core.asm#L3983) and [6368](https://github.com/pret/pokecrystal/blob/fabdd8e0196d1c50ee0a4a40823d0f8a0372d93c/engine/battle/core.asm#L6368). Do you think we should also replace them with `NUM_STATS - 1`?

Definitely yes, especially since there's that puzzled "`; Only the first five base stats are copied..`" comment which can now be more informative.

**Comment by Idain** [comment]
Done, @Rangi42. Feel free to further review my PR and merge it when you can.

**Pull request merged**
