### PR TITLE
Organize the engine/ directory

### PR DESCRIPTION
**Pull request by mid-kid**
This is an informed attempt at reorganizing the engine/ directory by
creating categorized subdirectories, in order to make it easier to
navigate and find things.

The directories created are as follows:
* engine/games: Contains all "minigames", things like the unown puzzle
and slot machine.
* engine/gfx: Contains all handling of graphics. From loading palettes
to playing animations.
* engine/link: Contains all multiplayer functionality.
* engine/menus: Contains all generic/misc. menus and menu code.
Other, more specialized menus are in their own subdirectories (pokedex,
pokegear, party menu, etc).
* engine/overworld: Contains all handling of the overworld. From loading
and connecting maps to wild encounters and the scripting engine.
* engine/pokegear: In the same vein as engine/pokedex, except it could
use some more splitting up.
* engine/pokemon: Contains everything related to manipulating pokemon
data. From the pokemon storage system to evolution and mail.
* engine/printer: Contains everything related to printing things as well
as the printer communication.
* engine/movies: Contains intro sequences, title screens and credits.
* engine/rtc: Contains all RTC-related things. Menus, hardware, misc
functions.
* engine/items: Contains all item-related things. Pack, item effects,
other item handlers.
* engine/tilesets: Contains all map-related graphics routines.
* engine/math: Contains all generic math-related routines.

Check the individual commit messages for more info.

### CODE REVIEW

**Comment by Rangi42** [comment]
Good start! Some suggestions:

* Rename `game` to `games` or `minigames`; "game" sounds like it's about the main Crystal game
* Same for `menu` → `menus`
* Also move files from `routines` to their relevant subdirectories, e.g. `switchpartymons.asm` to `pokemon`
* `title` includes the title screen, intro sequence, and ending credits; is there a better name?
* `init_gender.asm` and `intro_menu.asm` should go in `title`, or whatever it ends up being called
* I think some other `menu` files would be easier to find in role-based subdirectories:
   * `items` that includes `buy_sell_toss.asm`, `mart.asm`, `pack.asm`, `tmhm.asm`, `item_effects.asm`, and `items.asm`
   * `rtc` that includes `clock_reset.asm`, `delete_save_change_clock.asm`, `timeset.asm`, and `rtc.asm`
   * Maybe move `main_menu.asm` and `naming_screen.asm` to `title` (aka `intro`, `pregame`, `init`, I don't know what)

**Comment by mid-kid** [comment]
I agree with `game` -> `games` and `menu` -> `menus`. Will change that.

I completely ignored `routines` while making this. Will we require sorting through `routines`, or shall we just get the few that match these directories out, while leaving the rest there?

The intention of `title` was housing all the "cutscenes" or "full-screen animations you can't really interact with" if you will. There really isn't much more than the title screen and credits, so I thought `title` would work fine. `cutscenes` doesn't really sound appropriate and `animations` is just too ambiguous. That's the reason `init_gender` and `intro_menu` aren't in there.
We could, as you said, maybe expand the definition of this directory to house anything related to the main menu, but I have no idea what to define it as nor what to call it in a way that is intuitive.

Besides, `rtc.asm` and `item_effects.asm` which don't contain any menu code, I think splitting up `menu` further is an okay idea, but there isn't much more to categorize other than `items` and `rtc`, the leftover 9 files are pretty much one-offs, unless you want to categorize the menu implementations, `menu.asm`, `menu2.asm` and `scrolling_menu.asm`.

And yeah, I had completely forgotten about updating `docs/` and `constants/`, will do that by the end of this.

**Comment by Rangi42** [comment]
Any files in `routines` that don't correspond to a subdirectory can just stay there.

Since the intro and credits are the only "full-screen animations you can't really interact with", and the title screen is more like a menu anyway (responds to A, Start, and Down+B+Select+Start), how about two dirs for `intro` and `credits`? `intro` could then include all the pre-game stuff: the intro animation, title screen, main menu, and gender selection.

Besides moving some `menu` files into `rtc`, `items`, and `title`/`intro`/`start`/whatever, I'm fine with keeping the general-purpose `menus` subdirectory for the rest.

**Comment by mid-kid** [comment]
That'd make `credits` a one-file directory, though. I'd like to keep intro sequence and credits in the same directory if at all possible.

I've probably misinterpreted your previous message, I was talking about making `rtc` and `items` directories _inside_ the `menus` directory. Having them outside and include `rtc.asm` and `item_effects.asm` makes more sense, yes.

**Comment by Rangi42** [comment]
`engine/menus/rtc/*.asm` and `engine/menus/items/*.asm` is deep nesting for not much content; and I'm proposing that they include the RTC and item effect engines as well as the front-end menu code.

You're right that two files isn't enough to justify `credits`. Maybe call it `pre_post` or `intro_credits`?

**Comment by Rangi42** [comment]
* `tmhm.asm` should go in `items`, it's mostly code for managing the TM Pocket, with a little Pokémon related code for teaching moves that really just wraps `callfar KnowsMove` and `predef LearnMove`.
* Maybe add a `tilesets` subdirectory with `map_palettes.asm`, `mapgroup_roofs.asm`, `tileset_anims.asm`, `tileset_palettes.asm`, and `timeofdaypals.asm` moved from `gfx`; they're like a cross between `gfx` and `overworld` code anyway.
* These `routines` files have corresponding subdirectories:
   * `checknickerrors.asm`: `pokemon`
   * `checktime.asm`: `rtc`
   * `correcterrorsinplayerparty.asm`: `pokemon`
   * `loadpushoam.asm`: `gfx`
   * `phonering_copytilemapatonce.asm`: `phone`
   * `placewaitingtext.asm`: `link`
   * `playslowcry.asm`: `pokemon`
   * `savemenu_copytilemapatonce.asm`: `menus`
   * `townmap_convertlinebreakcharacters.asm`: `pokegear`
* Other subdirectories you could justify:
   * `math`, including `getsquareroot.asm`, `math.asm`, `printnum.asm`, and `sine.asm`
   * `save`, including `save.asm`, `checksave.asm`, `emptyallsrambanks.asm`, and `savemenu_copytilemapatonce.asm`
   * `predef`, including `predef.asm` and `flagpredef.asm` (okay, not this one)
* `money.asm` arguably belongs in `events`, since it's just the implementations of the script commands `(give|take|check)(money|coins)`
* Also, I was surprised to find `scripting.asm` in `overworld` and not `events`.
* `overworld` could have a `map_objects` subdirectory split out for the map_object and movement related files.
* `pokemon` could have a `pc` subdirectory split out for `billspc.asm`, `billspctop.asm`, `move_mon.asm`, and `move_mon_wo_mail.asm`

**Comment by Rangi42** [comment]
Also, I don't think ~20-25 files is too many for one directory. 26 files in GitHub fits on one 1080p screen, and even more are visible in a local copy in Explorer.

Adding `pc` and `map_objects` should get `pokemon` and `overworld` closer to 20 files each, which is not unusual.

**Comment by yenatch** [comment]
`gfx/gbc_only.asm` should go into `title/` and renamed `scene/`
`gfx/evolution_animation.asm` should go into `pokemon/` or `scene/`
`gfx/trade_animation.asm` should go into `link/` or `scene/`

**Comment by Rangi42** [comment]
Given that "scene" is the new name for "trigger", can that be called something else? Maybe `cutscenes/`.

**Comment by yenatch** [comment]
i don't think it's ambiguous, but what about `movie/`

**Comment by mid-kid** [comment]
Sorry for my long absence. I've just pushed a new commit, implementing some of the suggestions.

I didn't create `math`, nor `save`. Instead, I simply moved `save.asm` to `menus/`. While I'm aware most of it isn't menu related, it fits there just as well as anywhere, especially considering we moved a bunch of files elsewhere, and `intro_menu.asm` mostly contains initialization routines as well.

`scripting.asm` is in `overworld` because it's the implementation of the scripting engine. I'd like to keep it and `events/` separate for the same reason `effect_commands.asm` and `move_effects/` are separate: The former hosts the engine and generic commands, the latter hosts the individual and more specialized commands.

For this reason, too, I've taken `events/` to be defined as containing the implementations of individual scripting commands, and moved some files there accordingly (`checktime.asm`, `checksave.asm`, `engine_flags.asm`, `money.asm`, `playslowcry.asm`).

I'm still not entirely convinced `tilesets/` warrants an entirely separate directory, but I hope the definition I've given it is fitting enough. I'm otherwise satisfied with the current state.

**Comment by Rangi42** [comment]
Can `routines` either be renamed to `misc` or distributed into more subdirs? Even if it means creating relatively small ones?

- emptyallsrambanks.asm: only called by rtc/delete_save_change_clock.asm, so put it in `rtc`?
- flagpredef.asm: `predef`-related
- getsquareroot.asm: `math`-related
- initlist.asm: only called by link/link.asm, so `link`
- math.asm: `math`-related
- predef.asm: `predef`-related
- printnum.asm: `math`-related
- sine.asm: `math`-related
- unreferenced_getgen1trainerclassname.asm: unreferenced, but maybe it could go in `events` or `battle` (or simply a one-file `unused` subdir, which could also hold debug.asm and unused_title.asm)

I know `predef` would be a two-file subdir, but if the other files move out into `math` etc then `routines` will be two-file anyway; and we've already eliminated other misc/unknown subdirs (with the exception of gfx/unknown which is all mobile-related or unused).

**Comment by mid-kid** [comment]
I'm fine with `math`, but I'd rather include predef somewhere instead of creating a directory. Would predef work in top-level `engine`? It is related to practically everything in engine, after all.

Also, I was thinking of splitting up `rtc/delete_save_change_clock.asm` into the change clock and delete save parts. I'd move the save deletion to `menus/`, to be next to save, and `emptyallsrambanks.asm` along with it. After all, `_DeleteSaveData` and `_ResetClock` don't depend on one another and are called separately from `menus/intro_menu.asm`.

**Comment by Rangi42** [comment]
Top-level `engine` is OK, although they'd be the only two files there. But none of the subdirs make sense for it, since they're all game-logic-related and predefs are a lower-level concept.

Good plan re: delete_save_change_clock.asm.

**Comment by mid-kid** [comment]
Okay. That should be everything. If everyone's fine with the current state, I'll adapt `constants/` and `docs/` to accomodate the relocations soon.

**Comment by Rangi42** [comment]
Just one more thing: "flagpredef.asm" is a remnant from when `SmallFarFlagAction` was called `FlagPredef`. It's only predef-related because `SmallFarFlagAction` is a predef, but so are many routines. How about "smallfarflagaction.asm" or "smallflag.asm" (parallel to engine_flags.asm and home/flag.asm)?

**Pull request merged**
