### PR TITLE
group maps into directories by landmark

### PR DESCRIPTION
**Pull request by yenatch**
adding another map reorg to the pile

### CODE REVIEW

**Comment by roukaour** [comment]
(Supersedes #386 .)

**Comment by roukaour** [comment]
These maps can be renamed for consistency, regardless of whether this exact subdirectory PR is merged:

- `CianwoodCityPhotoStudio` → CianwoodPhotoStudio`
- `LavenderTownSpeechHouse` → LavenderSpeechHouse`
- `Route5SaffronCityGate` → Route5SaffronGate`
- `Route1718Gate` → Route17_18Gate`
- `Route2946Gate` → Route29_46Gate`
- `BetaTeakCity.blk` → BetaEcruteakCity.blk`
- `BetaSSAquaInsideCutOut` → `BetaFastShipInsideCutOut`
- `BetaCinnabarIslandPokemonLabHallway.blk → `BetaCinnabarPokemonLabHallway.blk`
- `BetaCinnabarIslandPokemonLabRoom1.blk → `BetaCinnabarPokemonLabRoom1.blk`
- `BetaCinnabarIslandPokemonLabRoom2.blk → `BetaCinnabarPokemonLabRoom2.blk`
- `BetaCinnabarIslandPokemonLabRoom3.blk → `BetaCinnabarPokemonLabRoom3.blk`

(Renaming the two-route gates makes them sort correctly when using a "natural sort" like File Explorer, and IMO is easier to read. But if underscores are too exceptional, then never mind them.)

**Comment by TheMostCuriousThing** [comment]
I don't remember the consensus on this change (except that there more or less wasn't one). I'm ambivalent on the reorganization itself, but I *really really* appreciate `blockdata.asm`, `map_headers.asm`, `second_map_headers.asm` (whatever [their ultimate name](https://github.com/pret/pokecrystal/issues/441)) getting their own directory level.

**Comment by roukaour** [comment]
I would kind of like, as an immediate partial fix, to move the "metadata" files into data/, for both maps/ and tilesets/.

This would mean:

* data/maps/map_headers.asm
* data/maps/map_headers_2.asm (from maps/second_map_headers.asm)
* data/maps/block_data.asm
* data/tilesets/tilesets.asm
* data/tilesets/data.asm
* data/tilesets/palette_maps.asm
* engine/routines/LoadMapGroupRoof.asm (from tilesets/roofs.asm)
* engine/tileset_palettes.asm (from tilesets/special_palettes.asm)
* engine/tileset_anims.asm (from tilesets/animations.asm)

That way, maps/ and tilesets/ would both be just catch-all directories for the not-yet-organized map and tileset data, and we can at least make the metadata easy to edit until the data's final organization is determined.

**Pull request closed without merging**
