### PR TITLE
Build Australian Crystal.

### PR DESCRIPTION
**Pull request by iimarckus**
https://github.com/mid-kid/pokecrystal/commit/2fae5a73b906094501b1595b065b2766e8c90e42

### CODE REVIEW

**Comment by Kroc** [comment]
Trust the Aussies to mess about with the pokies! :)

**Comment by Asday** [comment]
@Kroc Bunch of hand-wringing about gambling shaking my smh to be tbh.

**Comment by Kroc** [comment]
23a35bbaff659df05afe7fd8c31c170b

**Comment by mid-kid** [comment]
Frankly I didn't want to submit this upstream because I wanted to try to do a proper i18n fork, with all of the languages, in a way that doesn't inconvenience people that don't want to work on anything other than the english version. Though, I suppose this one is close enough to the english version to not really be much of a problem.

**Comment by iimarckus** [comment]
Yes, if this weren’t nearly identical to the English version it would be worth doing in a different way.

**Comment by Rangi42** [comment]
Please standardize `IF`/`ELSE`/`ENDC` to `if`/`else`/`endc`.

**Comment by Rangi42** [comment]
Also, might as well rename the `mobile/stadium/` files to `stadium2.bin`, `stadium2_11.bin`, and `stadium2_aus.bin` while we're adding a 3rd one.

**Comment by Rangi42** [comment]
One more request: `pokecrystal-aus.gbc` instead of `pokecrystalaus.gbc`. It's more legible, especially for if we add more languages:

```
f4cd194bdee0d04ca4eac29e09b8e4e9d818c133 *pokecrystal.gbc
f2f52230b536214ef7c9924f483392993e226cfb *pokecrystal11.gbc
a0fc810f1d4e124434f7be2c989ab5b5892ddf36 *pokecrystal-aus.gbc
95127b901bbce2407daf43cce9f45d4c27ef635d *pokecrystal-jpn.gbc
889a06fc0bb863666865aa69def0adf97945ac2a *pokecrystal-esp.gbc
accb584293ba056152f1fd908439b019017ff2fe *pokecrystal-deu.gbc
c055992b16b7399c687647725cdd1f4f13a2f75c *pokecrystal-fra.gbc
6cee05e5b95beeae74b8365ad18ec4a07a8c4af8 *pokecrystal-ita.gbc
```

**Comment by iimarckus** [comment]
Fixed case of conditionals.

Renamed Stadium 2 blobs.

Changed output filename to pokecrystal-au.gbc. I went with a two‐character country code since we already used those for pokered.

**Comment by kanzure** [comment]
Forgot README update for new `pokecrystal-au` build target.

**Comment by Rangi42** [comment]
@kanzure What's the ROM name? I can't find one for an Australian rip.

Others:

- Pocket Monsters - Crystal Version (J) [C][!].gbc `sha1: 95127b901bbce2407daf43cce9f45d4c27ef635d`
- Pokemon - Edicion Cristal (S) [C][!].gbc `sha1: 889a06fc0bb863666865aa69def0adf97945ac2a`
- Pokemon - Kristall-Edition (G) [C][!].gbc `sha1: accb584293ba056152f1fd908439b019017ff2fe`
- Pokemon - Version Cristal (F) [C][!].gbc `sha1: c055992b16b7399c687647725cdd1f4f13a2f75c`
- Pokemon - Versione Cristallo (I) [C][!].gbc `sha1: 6cee05e5b95beeae74b8365ad18ec4a07a8c4af8`

**Comment by Rangi42** [comment]
Ah, never mind: https://64bitorless.wordpress.com/rom-suffix-explanations/

**Pull request merged**
