### PR TITLE
Add fix for Sunny Day moves used by the "Smart" AI

### PR DESCRIPTION
**Pull request by coltongit**
Fixes https://github.com/pret/pokecrystal/issues/807

### CODE REVIEW

**Comment by ElectroDeoxys** [comment]
The section title is inaccurate. The AI doesn't discourage these moves at all. The AI uses this list to figure out whether it's advantageous to use Sunny Day. So if the Enemy's Pokémon has any of the moves listed, it will encourage the use of Sunny Day.

**Comment by coltongit** [comment]
right, my wording must've been a bit off

**Comment by coltongit** [comment]
@ElectroDeoxys fixed the misnomer, hopefully this is better

**Comment by ElectroDeoxys** [comment]
It's still misleading. The AI _doesn't_ encourage these moves. Like I said, it's a list of moves to figure whether it should encourage Sunny Day or not.

**Comment by coltongit** [comment]
There isn't much of a better way to describe this than what's currently there now. Hopefully now it isn't misleading.

**Comment by mid-kid** [comment]
"Sunny Day-encouraging moves" → "moves that encourage Sunny Day"

I was confused as well, please change this.

**Comment by coltongit** [comment]
> 
> 
> "Sunny Day-encouraging moves" → "moves that encourage Sunny Day"
> 
> I was confused as well, please change this, and squash commits.

Change applied, I forget if you can git squash multiple commits already committed, been a while

**Comment by mid-kid** [comment]
That's the exact purpose of squashing, but sure, I'll do it.

**Pull request merged**
